---
# Uses Ubuntu 'trusty' distribution
sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.13.0

language: ruby

install:

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose version

  - echo "slug" $TRAVIS_REPO_SLUG
  - echo "branch" $TRAVIS_BRANCH

  - echo "pr slug" $TRAVIS_PULL_REQUEST_SLUG
  - echo "pr branch" $TRAVIS_PULL_REQUEST_BRANCH

  - echo "event" $TRAVIS_EVENT_TYPE

  # - BE_REPO=voteamerica/backend
  - BE_REPO=jkbits1/backend

  # - BE_BRANCH=master
  - BE_BRANCH=docker-test

  - echo BE REPO $BE_REPO
  - echo BE BRANCH $BE_BRANCH

  - echo install

  - pwd

  # - git clone --single-branch --branch master https://github.com/voteamerica/backend $HOME/build/voteamerica/be
  - git clone --single-branch --branch $BE_BRANCH https://github.com/$BE_REPO $HOME/build/voteamerica/be

  - ls $HOME/build/voteamerica/be

before_script:
  - echo before

  - ls $HOME/build/voteamerica/be

  - $HOME/build/voteamerica/be/docker/specific-machine-test-travis-fe.sh cp-front-end   R $TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_EVENT_TYPE $TRAVIS_PULL_REQUEST_SLUG $TRAVIS_PULL_REQUEST_BRANCH

# these commands create specific machines for test runner, node app and db
# if working on a dev branch of the backend, uncomment the relevant machines and
# set the repo/branch that contains the backend dev code
  - $HOME/build/voteamerica/be/docker/specific-machine-test-travis-fe.sh cp-test-runner R $BE_REPO $BE_BRANCH
  - $HOME/build/voteamerica/be/docker/specific-machine-test-travis-fe.sh cp-nodejs      R $BE_REPO $BE_BRANCH
  - $HOME/build/voteamerica/be/docker/specific-machine-test-travis-fe.sh cp-pg-server   R $BE_REPO $BE_BRANCH

  # - docker-compose -f $HOME/build/voteamerica/be/docker/compose/full-stack-test/docker-compose-test.yml build --build-arg REPO=https://github.com/jkbits1/backend --build-arg BRANCH_NAME=docker-test --build-arg CACHEBUST=$(date +%s) cp-test-runner
  # - docker-compose -f $HOME/build/voteamerica/be/docker/compose/full-stack-test/docker-compose-test.yml build --build-arg REPO=https://github.com/jkbits1/backend --build-arg BRANCH_NAME=docker-test --build-arg CACHEBUST=$(date +%s) cp-nodejs
  # - docker-compose -f $HOME/build/voteamerica/be/docker/compose/full-stack-test/docker-compose-test.yml build --build-arg REPO=https://github.com/jkbits1/backend --build-arg BRANCH_NAME=docker-test --build-arg CACHEBUST=$(date +%s) cp-pg-server

  - docker-compose -f $HOME/build/voteamerica/be/docker/compose/full-stack-test/docker-compose-test.yml up -d

script:
  - $HOME/build/voteamerica/be/docker/compose-tests.sh pause-cancel2

after_script:
  - docker-compose -f $HOME/build/voteamerica/be/docker/compose/full-stack-test/docker-compose-test.yml down
